# docker-compose -f docker-compose.yaml -- up -d
# default filename is docker-compose.yaml
# version: "2"
# services:
#     db:
#         image: mysql:8.0.16
#         command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
#         ports:
#             - "3307:3306"
#         environment:
#             MYSQL_DATABASE: myDb
#             MYSQL_USER: user
#             MYSQL_PASSWORD: test
#             MYSQL_ROOT_PASSWORD: test
#         volumes:
#             - ./dump:/docker-entrypoint-initdb.d
#             - persistent:/var/lib/mysql
#         networks:
#             - default
#     phpmyadmin:
#         image: phpmyadmin/phpmyadmin:4.8
#         links:
#             - db:db
#         ports:
#             - 80:80
#         environment:
#             MYSQL_USER: user
#             MYSQL_PASSWORD: test
#             MYSQL_ROOT_PASSWORD: test
# volumes:
#     persistent:

version: "3.1"
services:
    db:
        image: mariadb:10.3
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: amuletmhs
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - db:db
        ports:
            - 80:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: